ARG MARIADB_VERSION=latest
FROM mariadb:latest

#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && chown -R mysql:root /var/lib/mysql/
COPY my.cnf /etc/my.cnf

CMD ["mysqld"]

EXPOSE 3306
