on:
  push:
    branches:
      - main

name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring
          tools: composer:v2
          coverage: none

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: dependencies-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-composer-

      - name: Get npm cache directory
        id: npmcache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.npmcache.outputs.dir }}
          key: dependencies-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: dependencies-npm-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Install npm dependencies
        run: npm ci --prefer-offline

      - name: Build frontend
        run: npm run production

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy stage=production
